### ISSUE TITLE
Unicredit Banks 

### ISSUE THREAD

**Issue by georgenturner** [okfn/datapackage_pipelines_od4tj#16]
###Unicredit CBCR is split into different tables for each type of subsidiary - this is the banks table. Table relates to issue No15

```yaml
-
  # Year
  year: 2014
  # EntityName
  entity: Unicredit
  inputs:
    # Path to the PDF you uploaded in the project
    - url: https://download-rl-of-the-file
      kind: pdf
      parameters:
        # Paste the dimensions of the selection you made in Tabula
        dimensions: [
    {
        "page": 2,
        "extraction_method": "lattice",
        "selection_id": "S1500904599861",
        "x1": 40.00399020599369,
        "x2": 502.7875174276734,
        "y1": 103.55339440307621,
        "y2": 242.68606255493168,
        "width": 462.78352722167966,
        "height": 139.13266815185546
    },
    {
        "page": 2,
        "extraction_method": "lattice",
        "selection_id": "U1500904599888",
        "x1": 40.00399020599369,
        "x2": 502.7875174276734,
        "y1": 255.5576944213867,
        "y2": 391.71426271972655,
        "width": 462.78352722167966,
        "height": 136.15656829833983
    },
    {
        "page": 2,
        "extraction_method": "lattice",
        "selection_id": "P1500904599909",
        "x1": 40.00399020599369,
        "x2": 502.7875174276734,
        "y1": 405.55312703857413,
        "y2": 538.7335954833984,
        "width": 462.78352722167966,
        "height": 133.1804684448242
    },
    {
        "page": 2,
        "extraction_method": "lattice",
        "selection_id": "N1500904599926",
        "x1": 40.00399020599369,
        "x2": 181.3687332479859,
        "y1": 551.5605858520507,
        "y2": 685.4850792602539,
        "width": 141.36474304199217,
        "height": 133.92449340820312
    },
    {
        "page": 3,
        "extraction_method": "lattice",
        "selection_id": "N1500904610727",
        "x1": 37.94527313232422,
        "x2": 515.6092996215821,
        "y1": 72.17042144775391,
        "y2": 210.55906463623046,
        "width": 477.6640264892578,
        "height": 138.38864318847655
    },
    {
        "page": 3,
        "extraction_method": "lattice",
        "selection_id": "B1500904615576",
        "x1": 29.760998535156247,
        "x2": 529.7457739257812,
        "y1": 215.7672393798828,
        "y2": 351.1797827148437,
        "width": 499.984775390625,
        "height": 135.41254333496093
    },
    {
        "page": 3,
        "extraction_method": "lattice",
        "selection_id": "E1500904620121",
        "x1": 39.43332305908203,
        "x2": 188.98234069824218,
        "y1": 356.3879574584961,
        "y2": 485.84830108642575,
        "width": 149.54901763916016,
        "height": 129.4603436279297
    }
]
  processing: {}
  model:
    # Define the fields of the table in order they appear in the table
    headers:
      # `string` type is default
      - name: country
      - name: commentary
      # `number` type if it's a number with decimal points
      # `currency` in [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217)
      # `factor` of the amount (e.g. 5.3 factor 1 million = 5300000)
      - name: turnover
        type: number
        currency: gbp
        factor: 1m
      - name: profit_before_tax
        type: number
        currency: gbp
        factor: 1m
      - name: total_tax_paid
        type: number
        currency: gbp
        factor: 1m
      - name: subsidies
        type: number
        currency: gbp
        factor: 1m
      - name: full_time_equivalents
        type: number

```
