### ISSUE TITLE
Unicredit Financial Institutions

### ISSUE THREAD

**Issue by georgenturner** [okfn/datapackage_pipelines_od4tj#17]
###Unicredit separates the type of subsidiary in to different tables. This is the Financial Institution Table, refers to Issue 15
```yaml
-
  # Year
  year: 2014
  # EntityName
  entity: Barclays
  inputs:
    # Path to the PDF you uploaded in the project
    - url: https://download-rl-of-the-file
      kind: pdf
      parameters:
        # Paste the dimensions of the selection you made in Tabula
        dimensions: [
    {
        "page": 4,
        "extraction_method": "lattice",
        "selection_id": "J1500904953814",
        "x1": 38.68929809570312,
        "x2": 505.19295013427734,
        "y1": 76.63457122802734,
        "y2": 203.8628399658203,
        "width": 466.5036520385742,
        "height": 127.22826873779296
    },
    {
        "page": 4,
        "extraction_method": "lattice",
        "selection_id": "W1500904976117",
        "x1": 33.48112335205078,
        "x2": 510.40112487792965,
        "y1": 206.09491485595703,
        "y2": 338.5313583374023,
        "width": 476.9200015258789,
        "height": 132.4364434814453
    },
    {
        "page": 4,
        "extraction_method": "lattice",
        "selection_id": "D1500904982315",
        "x1": 36.45722320556641,
        "x2": 479.8961013793945,
        "y1": 340.76343322753905,
        "y2": 476.17597656249995,
        "width": 443.43887817382813,
        "height": 135.41254333496093
    },
    {
        "page": 6,
        "extraction_method": "stream",
        "selection_id": "I1500904968458",
        "x1": 38.68929809570312,
        "x2": 505.19295013427734,
        "y1": 76.63457122802734,
        "y2": 203.8628399658203,
        "width": 466.5036520385742,
        "height": 127.22826873779296
    }
]
  processing: {}
  model:
    # Define the fields of the table in order they appear in the table
    headers:
      # `string` type is default
      - name: country
      - name: commentary
      # `number` type if it's a number with decimal points
      # `currency` in [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217)
      # `factor` of the amount (e.g. 5.3 factor 1 million = 5300000)
      - name: turnover
        type: number
        currency: gbp
        factor: 1m
      - name: profit_before_tax
        type: number
        currency: gbp
        factor: 1m
      - name: total_tax_paid
        type: number
        currency: gbp
        factor: 1m
      - name: subsidies
        type: number
        currency: gbp
        factor: 1m
      - name: full_time_equivalents
        type: number

```
