### ISSUE TITLE
Unicredit Insurance 

### ISSUE THREAD

**Issue by georgenturner** [okfn/datapackage_pipelines_od4tj#18]
###Unicredit separates the type of subsidiary in to different tables. This is the Insurance Institution Table, refers to Issue 15
```yaml
-
  # Year
  year: 2014
  # EntityName
  entity: Unicredit
  inputs:
    # Path to the PDF you uploaded in the project
    - url: https://download-rl-of-the-file
      kind: pdf
      parameters:
        # Paste the dimensions of the selection you made in Tabula
        dimensions: [
    {
        "page": 5,
        "extraction_method": "stream",
        "selection_id": "X1500905217727",
        "x1": 31.24904846191406,
        "x2": 279.00936126708984,
        "y1": 71.426396484375,
        "y2": 207.58296478271484,
        "width": 247.76031280517577,
        "height": 136.15656829833983
    },
    {
        "page": 6,
        "extraction_method": "stream",
        "selection_id": "D1500905217789",
        "x1": 38.68929809570312,
        "x2": 505.19295013427734,
        "y1": 76.63457122802734,
        "y2": 203.8628399658203,
        "width": 466.5036520385742,
        "height": 127.22826873779296
    }
] 
  processing: {}
  model:
    # Define the fields of the table in order they appear in the table
    headers:
      # `string` type is default
      - name: country
      - name: commentary
      # `number` type if it's a number with decimal points
      # `currency` in [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217)
      # `factor` of the amount (e.g. 5.3 factor 1 million = 5300000)
      - name: turnover
        type: number
        currency: gbp
        factor: 1m
      - name: profit_before_tax
        type: number
        currency: gbp
        factor: 1m
      - name: total_tax_paid
        type: number
        currency: gbp
        factor: 1m
      - name: subsidies
        type: number
        currency: gbp
        factor: 1m
      - name: full_time_equivalents
        type: number

```
