### ISSUE TITLE
Unicredit Non-Financial Institutions

### ISSUE THREAD

**Issue by georgenturner** [okfn/datapackage_pipelines_od4tj#19]
### Unicredit splits out the subsidiaries into different tables. This is the non-financial institution table
```yaml
-
  # Year
  year: 2014
  # EntityName
  entity: Unicredit
  inputs:
    # Path to the PDF you uploaded in the project
    - url: https://download-rl-of-the-file
      kind: pdf
      parameters:
        # Paste the dimensions of the selection you made in Tabula
        dimensions: [
    {
        "page": 5,
        "extraction_method": "stream",
        "selection_id": "T1500905378771",
        "x1": 33.48112335205078,
        "x2": 502.9608752441406,
        "y1": 217.9993142700195,
        "y2": 340.0194082641601,
        "width": 469.47975189208984,
        "height": 122.02009399414062
    },
    {
        "page": 5,
        "extraction_method": "stream",
        "selection_id": "X1500905384934",
        "x1": 33.48112335205078,
        "x2": 344.4835580444336,
        "y1": 346.7156329345703,
        "y2": 466.5036520385742,
        "width": 311.0024346923828,
        "height": 119.78801910400391
    }
]
  processing: {}
  model:
    # Define the fields of the table in order they appear in the table
    headers:
      # `string` type is default
      - name: country
      - name: commentary
      # `number` type if it's a number with decimal points
      # `currency` in [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217)
      # `factor` of the amount (e.g. 5.3 factor 1 million = 5300000)
      - name: turnover
        type: number
        currency: gbp
        factor: 1m
      - name: profit_before_tax
        type: number
        currency: gbp
        factor: 1m
      - name: total_tax_paid
        type: number
        currency: gbp
        factor: 1m
      - name: subsidies
        type: number
        currency: gbp
        factor: 1m
      - name: full_time_equivalents
        type: number

```
